# Generated by Django 4.0.5 on 2022-07-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=150)),
                ('edad', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('ecuatoriana', 'Ecuatoriana'), ('peruana', 'Peruana'), ('colombiana', 'Colombiana')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Propietario',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoDepartamento', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('numeroCuartos', models.IntegerField()),
                ('numeroBanios', models.IntegerField()),
                ('valorAlicuota', models.IntegerField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='administrativo.propietario')),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
